package Problem

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
class Problem02 extends Problem {
  override def run(): String = {
    var total = 2
    var value1:Int = 1
    var value2:Int = 2

    while (value2 < 4000000) {
      val term:Int = value1 + value2
      value1 = value2
      value2 = term

      if (term % 2 == 0) total += term
    }

    "Sum of even numbers: " + total
  }
}
